### ISSUE TITLE
Should handle empty json as that is not an unusual condition

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Goldark/ng-json-explorer#12]
Hello, in my app data is brought down via api from a server so there is no immediate value in the binding to the json explorer and as a result a nasty parse error is displayed in the console.

To work around I simply set a fake bit of json before the view goes to get the json from the api which avoids the error.

However this is really a bug I think as that is not an unusual condition.

I suggest that the piece of code in line 188:

      var json = JSON.parse(val);

Be modified to handle the very likely event that val is undefined or empty and *not* attempt to parse empty json so that a JSON parse error is not displayed in console unnecessarily.

**Comment by odra** [comment]
This shouldn't be a problem now.
