### ISSUE TITLE
Explorer does not display

### ISSUE THREAD

**Issue by vincentlawlor** [Goldark/ng-json-explorer#19]
Hi guys,

I have tried this in a few apps now and aside from the demo I cannot get it to work.

I always end up with something like the following when I look at the element.

"\<json-explorer json-data="{...}" class="ng-isolate-scope"\>\</json-explorer\>"

where {...} is the json data

{ "id": "54cbbbc8bf3cba42aea6ffc4",
					"index": 0,
					"guid": "0127d734-75a3-4d76-8ad5-8af0478043dd",
					"isActive": false,
					"balance": "$3,775.10",
					"picture": "http://placehold.it/32x32",
					"age": 22,
					"eyeColor": "brown",
					"name": "Arnold Romero",
					"gender": "male",
					"company": "BUZZOPIA",
					"email": "arnoldromero@buzzopia.com",
					"phone": "+1 (973) 531-2834",
					"address": "999 Rapelye Street, Fowlerville, Illinois, 1664",
					"about": "Eiusmod ex velit voluptate veniam culpa. Cupidatat aliqua consectetur reprehenderit cupidatat pariatur sunt velit ut ad non veniam id proident fugiat. Aute aliquip consequat ullamco incididunt cupidatat. Nostrud pariatur eu ex deserunt pariatur mollit reprehenderit sunt in qui. Velit proident deserunt quis commodo esse duis consectetur Lorem magna nostrud culpa.\r\n",
					"registered": "2014-05-12T12:59:32 +03:00",
					"latitude": 20.153763,
					"longitude": 42.329199,
					"tags": [
						"ut",
						"ad",
						"consequat",
						"eu",
						"ea",
						"do",
						"aliqua"
					],
					"friends": [
						{
							"id": 0,
							"name": "Terra Booker"
						},
						{
							"id": 1,
							"name": "Gilmore Saunders"
						},
						{
							"id": 2,
							"name": "Nash Riggs"
						}
					],
					"greeting": "Hello, Arnold Romero! You have 9 unread messages.",
					"favoriteFruit": "banana"
}

**Comment by vincentlawlor** [comment]
Tried the same thing with another formatter in my app and it works fine.
Exact same install process etc.

**Comment by odra** [comment]
I got it to work, how are you linking the json data into the directive? Directly from the scope?

**Comment by jorntnordahl** [comment]
I ended up with the same issue in a modal dialog. I was able to get it to work in a normal view, but in my modal dialog, the same happens as described above. Using $modal to open the modal dialog.

**Comment by facka** [comment]
Please update the readme file as it says json-data in the attribute name
